package integration.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-04-26T15:18:40.533+05:30
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://API.Integration/", name = "DataOrder30")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface DataOrder30 {

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getMasterProjectIDRequest", output = "http://API.Integration/DataOrder30/getMasterProjectIDResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public IntegerResult getMasterProjectID(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getProjectNameRequest", output = "http://API.Integration/DataOrder30/getProjectNameResponse")
    @WebResult(name = "StringResult", targetNamespace = "http://API.Integration/", partName = "StringResult")
    public StringResult getProjectName(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getOrderObjectRequest", output = "http://API.Integration/DataOrder30/getOrderObjectResponse")
    @WebResult(name = "OrderResult", targetNamespace = "http://API.Integration/", partName = "OrderResult")
    public OrderResult getOrderObject(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getOrderConfirmationsRequest", output = "http://API.Integration/DataOrder30/getOrderConfirmationsResponse")
    @WebResult(name = "StringArrayResult", targetNamespace = "http://API.Integration/", partName = "StringArrayResult")
    public StringArrayResult getOrderConfirmations(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/setEN15038RequestedRequest", output = "http://API.Integration/DataOrder30/setEN15038RequestedResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result setEN15038Requested(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "isEN15038", name = "isEN15038")
        boolean isEN15038,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/updateRequest", output = "http://API.Integration/DataOrder30/updateResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result update(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "OrderIN", name = "OrderIN")
        OrderIN orderIN,
        @WebParam(partName = "enableNullOrEmptyValues", name = "enableNullOrEmptyValues")
        boolean enableNullOrEmptyValues
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/insertRequest", output = "http://API.Integration/DataOrder30/insertResponse")
    @WebResult(name = "IntegerResult", targetNamespace = "http://API.Integration/", partName = "IntegerResult")
    public IntegerResult insert(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/setProjectmanagerIDRequest", output = "http://API.Integration/DataOrder30/setProjectmanagerIDResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result setProjectmanagerID(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "resourceID", name = "resourceID")
        int resourceID,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/deleteRequest", output = "http://API.Integration/DataOrder30/deleteResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result delete(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getCreationDateRequest", output = "http://API.Integration/DataOrder30/getCreationDateResponse")
    @WebResult(name = "DateResult", targetNamespace = "http://API.Integration/", partName = "DateResult")
    public DateResult getCreationDate(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getRateRequest", output = "http://API.Integration/DataOrder30/getRateResponse")
    @WebResult(name = "DoubleResult", targetNamespace = "http://API.Integration/", partName = "DoubleResult")
    public DoubleResult getRate(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/setDeliveryDeadlineRequest", output = "http://API.Integration/DataOrder30/setDeliveryDeadlineResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result setDeliveryDeadline(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "deliveryDeadline", name = "deliveryDeadline")
        javax.xml.datatype.XMLGregorianCalendar deliveryDeadline,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getDeliveryDeadlineRequest", output = "http://API.Integration/DataOrder30/getDeliveryDeadlineResponse")
    @WebResult(name = "DateResult", targetNamespace = "http://API.Integration/", partName = "DateResult")
    public DateResult getDeliveryDeadline(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getProjectmanagerIDRequest", output = "http://API.Integration/DataOrder30/getProjectmanagerIDResponse")
    @WebResult(name = "IntegerResult", targetNamespace = "http://API.Integration/", partName = "IntegerResult")
    public IntegerResult getProjectmanagerID(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/setCustomerIDRequest", output = "http://API.Integration/DataOrder30/setCustomerIDResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result setCustomerID(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "customerID", name = "customerID")
        int customerID,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod(operationName = "getDocuments_Within_SourceFolder_ByLanguage")
    @Action(input = "http://API.Integration/DataOrder30/getDocuments_Within_SourceFolder_ByLanguageRequest", output = "http://API.Integration/DataOrder30/getDocuments_Within_SourceFolder_ByLanguageResponse")
    @WebResult(name = "StringArrayResult", targetNamespace = "http://API.Integration/", partName = "StringArrayResult")
    public StringArrayResult getDocumentsWithinSourceFolderByLanguage(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "language", name = "language")
        java.lang.String language,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getPropertyRequest", output = "http://API.Integration/DataOrder30/getPropertyResponse")
    @WebResult(name = "IntegerResult", targetNamespace = "http://API.Integration/", partName = "IntegerResult")
    public StringResult getProperty(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID,
        @WebParam(partName = "propertyNameEnglish", name = "propertyNameEnglish")
        java.lang.String propertyNameEnglish
    );

    @WebMethod(operationName = "deregisterCallback_Observer")
    @Action(input = "http://API.Integration/DataOrder30/deregisterCallback_ObserverRequest", output = "http://API.Integration/DataOrder30/deregisterCallback_ObserverResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result deregisterCallbackObserver(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "OrderID", name = "OrderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/setMasterProjectIDRequest", output = "http://API.Integration/DataOrder30/setMasterProjectIDResponse")
    @WebResult(name = "IntegerResult", targetNamespace = "http://API.Integration/", partName = "IntegerResult")
    public Result setMasterProjectID(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID,
        @WebParam(partName = "MasterProjectID", name = "MasterProjectID")
        int masterProjectID
    );

    @WebMethod(operationName = "registerCallback_Notify")
    @Action(input = "http://API.Integration/DataOrder30/registerCallback_NotifyRequest", output = "http://API.Integration/DataOrder30/registerCallback_NotifyResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result registerCallbackNotify(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "ServerAuthenticationString", name = "ServerAuthenticationString")
        java.lang.String serverAuthenticationString,
        @WebParam(partName = "ServerAddress", name = "ServerAddress")
        java.lang.String serverAddress,
        @WebParam(partName = "EventType", name = "EventType")
        int eventType
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getOrderIDRequest", output = "http://API.Integration/DataOrder30/getOrderIDResponse")
    @WebResult(name = "IntegerResult", targetNamespace = "http://API.Integration/", partName = "IntegerResult")
    public IntegerResult getOrderID(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "displayNo", name = "displayNo")
        java.lang.String displayNo
    );

    @WebMethod(operationName = "registerCallback_Observer")
    @Action(input = "http://API.Integration/DataOrder30/registerCallback_ObserverRequest", output = "http://API.Integration/DataOrder30/registerCallback_ObserverResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result registerCallbackObserver(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "ServerAuthenticationString", name = "ServerAuthenticationString")
        java.lang.String serverAuthenticationString,
        @WebParam(partName = "ServerAddress", name = "ServerAddress")
        java.lang.String serverAddress,
        @WebParam(partName = "OrderID", name = "OrderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getTemplateListRequest", output = "http://API.Integration/DataOrder30/getTemplateListResponse")
    @WebResult(name = "TemplateListResult", targetNamespace = "http://API.Integration/", partName = "TemplateListResult")
    public TemplateListResult getTemplateList(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getCustomerIDRequest", output = "http://API.Integration/DataOrder30/getCustomerIDResponse")
    @WebResult(name = "IntegerResult", targetNamespace = "http://API.Integration/", partName = "IntegerResult")
    public IntegerResult getCustomerID(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getDeliveryCommentRequest", output = "http://API.Integration/DataOrder30/getDeliveryCommentResponse")
    @WebResult(name = "StringResult", targetNamespace = "http://API.Integration/", partName = "StringResult")
    public StringResult getDeliveryComment(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/checkEN15038Request", output = "http://API.Integration/DataOrder30/checkEN15038Response")
    @WebResult(name = "BooleanResult", targetNamespace = "http://API.Integration/", partName = "BooleanResult")
    public BooleanResult checkEN15038(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getOrderObjectListRequest", output = "http://API.Integration/DataOrder30/getOrderObjectListResponse")
    @WebResult(name = "OrderListResult", targetNamespace = "http://API.Integration/", partName = "OrderListResult")
    public OrderListResult getOrderObjectList(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderIDList", name = "orderIDList")
        IntegerList orderIDList
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getLanguageCombinationRequest", output = "http://API.Integration/DataOrder30/getLanguageCombinationResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public StringArrayResult getLanguageCombination(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getSubjectRequest", output = "http://API.Integration/DataOrder30/getSubjectResponse")
    @WebResult(name = "StringResult", targetNamespace = "http://API.Integration/", partName = "StringResult")
    public StringResult getSubject(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/setSubjectRequest", output = "http://API.Integration/DataOrder30/setSubjectResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result setSubject(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "subject", name = "subject")
        java.lang.String subject,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod(operationName = "deregisterCallback_Notify")
    @Action(input = "http://API.Integration/DataOrder30/deregisterCallback_NotifyRequest", output = "http://API.Integration/DataOrder30/deregisterCallback_NotifyResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result deregisterCallbackNotify(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "EventType", name = "EventType")
        int eventType
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/createOrderConfirmationRequest", output = "http://API.Integration/DataOrder30/createOrderConfirmationResponse")
    @WebResult(name = "StringResult", targetNamespace = "http://API.Integration/", partName = "StringResult")
    public StringResult createOrderConfirmation(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "template", name = "template")
        java.lang.String template,
        @WebParam(partName = "formatId", name = "formatId")
        int formatId,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getOrderObject2Request", output = "http://API.Integration/DataOrder30/getOrderObject2Response")
    @WebResult(name = "OrderResult", targetNamespace = "http://API.Integration/", partName = "OrderResult")
    public OrderResult getOrderObject2(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderNumber", name = "orderNumber")
        java.lang.String orderNumber
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/setCreationDateRequest", output = "http://API.Integration/DataOrder30/setCreationDateResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result setCreationDate(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "creationDate", name = "creationDate")
        javax.xml.datatype.XMLGregorianCalendar creationDate,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod(operationName = "insert_byTemplate")
    @Action(input = "http://API.Integration/DataOrder30/insert_byTemplateRequest", output = "http://API.Integration/DataOrder30/insert_byTemplateResponse")
    @WebResult(name = "IntegerResult", targetNamespace = "http://API.Integration/", partName = "IntegerResult")
    public IntegerResult insertByTemplate(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "OrderIN", name = "OrderIN")
        OrderIN orderIN,
        @WebParam(partName = "TemplateID", name = "TemplateID")
        int templateID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getRequestIdRequest", output = "http://API.Integration/DataOrder30/getRequestIdResponse")
    @WebResult(name = "IntegerResult", targetNamespace = "http://API.Integration/", partName = "IntegerResult")
    public IntegerResult getRequestId(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getOrderClosingDateRequest", output = "http://API.Integration/DataOrder30/getOrderClosingDateResponse")
    @WebResult(name = "DateResult", targetNamespace = "http://API.Integration/", partName = "DateResult")
    public DateResult getOrderClosingDate(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getCurrencyRequest", output = "http://API.Integration/DataOrder30/getCurrencyResponse")
    @WebResult(name = "StringResult", targetNamespace = "http://API.Integration/", partName = "StringResult")
    public StringResult getCurrency(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod(operationName = "getOrderNo_for_View")
    @Action(input = "http://API.Integration/DataOrder30/getOrderNo_for_ViewRequest", output = "http://API.Integration/DataOrder30/getOrderNo_for_ViewResponse")
    @WebResult(name = "StringResult", targetNamespace = "http://API.Integration/", partName = "StringResult")
    public StringResult getOrderNoForView(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/setCurrencyAndRateRequest", output = "http://API.Integration/DataOrder30/setCurrencyAndRateResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result setCurrencyAndRate(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID,
        @WebParam(partName = "currencyIsoCode", name = "currencyIsoCode")
        java.lang.String currencyIsoCode,
        @WebParam(partName = "rate", name = "rate")
        double rate
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getItemStatusRequest", output = "http://API.Integration/DataOrder30/getItemStatusResponse")
    @WebResult(name = "IntegerResult", targetNamespace = "http://API.Integration/", partName = "IntegerResult")
    public IntegerResult getItemStatus(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "sourceLanguage", name = "sourceLanguage")
        java.lang.String sourceLanguage,
        @WebParam(partName = "targetLanguage", name = "targetLanguage")
        java.lang.String targetLanguage,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod(operationName = "getDocuments_Within_FinalFolder")
    @Action(input = "http://API.Integration/DataOrder30/getDocuments_Within_FinalFolderRequest", output = "http://API.Integration/DataOrder30/getDocuments_Within_FinalFolderResponse")
    @WebResult(name = "StringArrayResult", targetNamespace = "http://API.Integration/", partName = "StringArrayResult")
    public StringArrayResult getDocumentsWithinFinalFolder(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getEN15038RequestedRequest", output = "http://API.Integration/DataOrder30/getEN15038RequestedResponse")
    @WebResult(name = "BooleanResult", targetNamespace = "http://API.Integration/", partName = "BooleanResult")
    public BooleanResult getEN15038Requested(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod(operationName = "getDocuments_Within_ReferenceFolder")
    @Action(input = "http://API.Integration/DataOrder30/getDocuments_Within_ReferenceFolderRequest", output = "http://API.Integration/DataOrder30/getDocuments_Within_ReferenceFolderResponse")
    @WebResult(name = "StringArrayResult", targetNamespace = "http://API.Integration/", partName = "StringArrayResult")
    public StringArrayResult getDocumentsWithinReferenceFolder(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/setProjectNameRequest", output = "http://API.Integration/DataOrder30/setProjectNameResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result setProjectName(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "name", name = "name")
        java.lang.String name,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/setCustomerContactIDRequest", output = "http://API.Integration/DataOrder30/setCustomerContactIDResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result setCustomerContactID(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "customerContactID", name = "customerContactID")
        int customerContactID,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod(operationName = "getDocuments_Within_ReferenceFolder_ByLanguage")
    @Action(input = "http://API.Integration/DataOrder30/getDocuments_Within_ReferenceFolder_ByLanguageRequest", output = "http://API.Integration/DataOrder30/getDocuments_Within_ReferenceFolder_ByLanguageResponse")
    @WebResult(name = "StringArrayResult", targetNamespace = "http://API.Integration/", partName = "StringArrayResult")
    public StringArrayResult getDocumentsWithinReferenceFolderByLanguage(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "language", name = "language")
        java.lang.String language,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/getCustomerContactIDRequest", output = "http://API.Integration/DataOrder30/getCustomerContactIDResponse")
    @WebResult(name = "IntegerResult", targetNamespace = "http://API.Integration/", partName = "IntegerResult")
    public IntegerResult getCustomerContactID(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/setPropertyRequest", output = "http://API.Integration/DataOrder30/setPropertyResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result setProperty(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID,
        @WebParam(partName = "propertyNameEnglish", name = "propertyNameEnglish")
        java.lang.String propertyNameEnglish,
        @WebParam(partName = "propertyValueEnglish", name = "propertyValueEnglish")
        java.lang.String propertyValueEnglish
    );

    @WebMethod(operationName = "getDocuments_Within_SourceFolder")
    @Action(input = "http://API.Integration/DataOrder30/getDocuments_Within_SourceFolderRequest", output = "http://API.Integration/DataOrder30/getDocuments_Within_SourceFolderResponse")
    @WebResult(name = "StringArrayResult", targetNamespace = "http://API.Integration/", partName = "StringArrayResult")
    public StringArrayResult getDocumentsWithinSourceFolder(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "orderID", name = "orderID")
        int orderID
    );

    @WebMethod
    @Action(input = "http://API.Integration/DataOrder30/insert2Request", output = "http://API.Integration/DataOrder30/insert2Response")
    @WebResult(name = "IntegerResult", targetNamespace = "http://API.Integration/", partName = "IntegerResult")
    public IntegerResult insert2(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "OrderIN", name = "OrderIN")
        OrderIN orderIN
    );
}
