package integration.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-04-26T15:18:39.993+05:30
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "DataRequest30Service", 
                  wsdlLocation = "file:/home/ttnd/Idea-Workspace/ISITransalation/ServerSide/src/main/resources/wsdl/DataRequest30.wsdl",
                  targetNamespace = "http://API.Integration/") 
public class DataRequest30Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://API.Integration/", "DataRequest30Service");
    public final static QName DataRequest30Port = new QName("http://API.Integration/", "DataRequest30Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/ttnd/Idea-Workspace/ISITransalation/ServerSide/src/main/resources/wsdl/DataRequest30.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DataRequest30Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/ttnd/Idea-Workspace/ISITransalation/ServerSide/src/main/resources/wsdl/DataRequest30.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DataRequest30Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DataRequest30Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataRequest30Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DataRequest30Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DataRequest30Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DataRequest30Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DataRequest30
     */
    @WebEndpoint(name = "DataRequest30Port")
    public DataRequest30 getDataRequest30Port() {
        return super.getPort(DataRequest30Port, DataRequest30.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataRequest30
     */
    @WebEndpoint(name = "DataRequest30Port")
    public DataRequest30 getDataRequest30Port(WebServiceFeature... features) {
        return super.getPort(DataRequest30Port, DataRequest30.class, features);
    }

}
