package integration.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-04-26T15:18:38.207+05:30
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "PlunetAPIService", 
                  wsdlLocation = "file:/home/ttnd/Idea-Workspace/ISITransalation/ServerSide/src/main/resources/wsdl/PlunetAPI.wsdl",
                  targetNamespace = "http://API.Integration/") 
public class PlunetAPIService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://API.Integration/", "PlunetAPIService");
    public final static QName PlunetAPIPort = new QName("http://API.Integration/", "PlunetAPIPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/ttnd/Idea-Workspace/ISITransalation/ServerSide/src/main/resources/wsdl/PlunetAPI.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PlunetAPIService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/ttnd/Idea-Workspace/ISITransalation/ServerSide/src/main/resources/wsdl/PlunetAPI.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PlunetAPIService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PlunetAPIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlunetAPIService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PlunetAPIService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PlunetAPIService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PlunetAPIService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PlunetAPI
     */
    @WebEndpoint(name = "PlunetAPIPort")
    public PlunetAPI getPlunetAPIPort() {
        return super.getPort(PlunetAPIPort, PlunetAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlunetAPI
     */
    @WebEndpoint(name = "PlunetAPIPort")
    public PlunetAPI getPlunetAPIPort(WebServiceFeature... features) {
        return super.getPort(PlunetAPIPort, PlunetAPI.class, features);
    }

}
