package integration.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-04-26T15:18:38.176+05:30
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://API.Integration/", name = "PlunetAPI")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PlunetAPI {

    @WebMethod
    @Action(input = "http://API.Integration/PlunetAPI/getVersionRequest", output = "http://API.Integration/PlunetAPI/getVersionResponse")
    @WebResult(name = "return", targetNamespace = "http://API.Integration/", partName = "return")
    public double getVersion();

    @WebMethod
    @Action(input = "http://API.Integration/PlunetAPI/logoutRequest", output = "http://API.Integration/PlunetAPI/logoutResponse")
    public void logout(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://API.Integration/PlunetAPI/loginRequest", output = "http://API.Integration/PlunetAPI/loginResponse")
    @WebResult(name = "return", targetNamespace = "http://API.Integration/", partName = "return")
    public java.lang.String login(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );
}
