package integration.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-04-26T15:18:41.004+05:30
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://API.Integration/", name = "RequestDocText25")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface RequestDocText25 {

    @WebMethod
    @Action(input = "http://API.Integration/RequestDocText25/getWordCountRequest", output = "http://API.Integration/RequestDocText25/getWordCountResponse")
    @WebResult(name = "IntegerResult", targetNamespace = "http://API.Integration/", partName = "IntegerResult")
    public IntegerResult getWordCount(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid
    );

    @WebMethod
    @Action(input = "http://API.Integration/RequestDocText25/setWordCountRequest", output = "http://API.Integration/RequestDocText25/setWordCountResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result setWordCount(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "wordCount", name = "wordCount")
        int wordCount
    );

    @WebMethod
    @Action(input = "http://API.Integration/RequestDocText25/setSourceText2Request", output = "http://API.Integration/RequestDocText25/setSourceText2Response")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result setSourceText2(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "sourceText", name = "sourceText")
        java.lang.String sourceText,
        @WebParam(partName = "encoding", name = "encoding")
        java.lang.String encoding
    );

    @WebMethod
    @Action(input = "http://API.Integration/RequestDocText25/insertRequest", output = "http://API.Integration/RequestDocText25/insertResponse")
    @WebResult(name = "IntegerResult", targetNamespace = "http://API.Integration/", partName = "IntegerResult")
    public IntegerResult insert(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "requestID", name = "requestID")
        int requestID
    );

    @WebMethod
    @Action(input = "http://API.Integration/RequestDocText25/updateRequest", output = "http://API.Integration/RequestDocText25/updateResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result update(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid
    );

    @WebMethod
    @Action(input = "http://API.Integration/RequestDocText25/deleteRequest", output = "http://API.Integration/RequestDocText25/deleteResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result delete(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "requestDocTextID", name = "requestDocTextID")
        int requestDocTextID
    );

    @WebMethod
    @Action(input = "http://API.Integration/RequestDocText25/setAdditionalInfoRequest", output = "http://API.Integration/RequestDocText25/setAdditionalInfoResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result setAdditionalInfo(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "additionalInfo", name = "additionalInfo")
        java.lang.String additionalInfo
    );

    @WebMethod
    @Action(input = "http://API.Integration/RequestDocText25/setSourceTextRequest", output = "http://API.Integration/RequestDocText25/setSourceTextResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result setSourceText(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "sourceText", name = "sourceText")
        java.lang.String sourceText
    );

    @WebMethod
    @Action(input = "http://API.Integration/RequestDocText25/getAdditionalInfoRequest", output = "http://API.Integration/RequestDocText25/getAdditionalInfoResponse")
    @WebResult(name = "StringResult", targetNamespace = "http://API.Integration/", partName = "StringResult")
    public StringResult getAdditionalInfo(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid
    );

    @WebMethod
    @Action(input = "http://API.Integration/RequestDocText25/setCustomerTextIDRequest", output = "http://API.Integration/RequestDocText25/setCustomerTextIDResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result setCustomerTextID(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "customerTextID", name = "customerTextID")
        int customerTextID
    );

    @WebMethod
    @Action(input = "http://API.Integration/RequestDocText25/getTargetTextRequest", output = "http://API.Integration/RequestDocText25/getTargetTextResponse")
    @WebResult(name = "StringResult", targetNamespace = "http://API.Integration/", partName = "StringResult")
    public StringResult getTargetText(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "targetLanguage", name = "targetLanguage")
        java.lang.String targetLanguage
    );

    @WebMethod
    @Action(input = "http://API.Integration/RequestDocText25/fetchRequest", output = "http://API.Integration/RequestDocText25/fetchResponse")
    @WebResult(name = "Result", targetNamespace = "http://API.Integration/", partName = "Result")
    public Result fetch(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "requestDocTextID", name = "requestDocTextID")
        int requestDocTextID
    );

    @WebMethod
    @Action(input = "http://API.Integration/RequestDocText25/getCustomerTextIDRequest", output = "http://API.Integration/RequestDocText25/getCustomerTextIDResponse")
    @WebResult(name = "IntegerResult", targetNamespace = "http://API.Integration/", partName = "IntegerResult")
    public IntegerResult getCustomerTextID(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid
    );

    @WebMethod(operationName = "getAll_ByRequestID")
    @Action(input = "http://API.Integration/RequestDocText25/getAll_ByRequestIDRequest", output = "http://API.Integration/RequestDocText25/getAll_ByRequestIDResponse")
    @WebResult(name = "IntegerArrayResult", targetNamespace = "http://API.Integration/", partName = "IntegerArrayResult")
    public IntegerArrayResult getAllByRequestID(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid,
        @WebParam(partName = "requestID", name = "requestID")
        int requestID
    );

    @WebMethod
    @Action(input = "http://API.Integration/RequestDocText25/getSourceTextRequest", output = "http://API.Integration/RequestDocText25/getSourceTextResponse")
    @WebResult(name = "StringResult", targetNamespace = "http://API.Integration/", partName = "StringResult")
    public StringResult getSourceText(
        @WebParam(partName = "UUID", name = "UUID")
        java.lang.String uuid
    );
}
